[package]
name = "cardgame_widgets"
version = "0.1.0"
authors = ["alanpoon"]

[dependencies]
conrod_core = { path ="../conrod/conrod_core"}
conrod_derive = { path = "../conrod/conrod_derive"}

[dev-dependencies]
image = "0.15.0"
find_folder = "0.3.0"