[package]
name = "cardgame_widgets"
version = "0.1.0"
authors = ["alanpoon"]

[dependencies]
conrod = { version ="0.57.0", features = ["glium","winit"]}
conrod_derive = "0.1.0"

[dev-dependencies]
image = "0.15.0"
find_folder = "0.3.0"